name: Deploy Website to cPanel
on:
  push:
    branches:
      - nhung  # Kích hoạt khi bạn push lên v2

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        # ĐÂY LÀ ĐIỂM QUAN TRỌNG NHẤT:
        local-dir: ./dist/   # Nó sẽ vào folder dist trên nhánh v2 để lấy file
        server-dir: ./hongnhung.site/      # Đổ vào thư mục gốc của hosting (public_html)